version: "3.7"

services:

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:7.9.3
    # entrypoint: ["/bin/bash", "-c", "chmod go-w /usr/share/packetbeat/packetbeat.yml; /usr/local/bin/docker-entrypoint"]
    command: setup -E setup.kibana.host=127.0.0.1:5601 # - this only needs to run the first time
    environment: 
      - output.elasticsearch.hosts=["127.0.0.1:9200"] 
    cap_add:
      - ALL
    network_mode: host
    volumes:
      - type: bind
        source: ./docker-elk/packetbeat.yml
        target: /usr/share/packetbeat/packetbeat.yml
        read_only: true
    depends_on:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ports:
      - "9200:9200/tcp"
    environment: 
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - cluster.name=dnsmetricslab
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - type: bind
        source: ./docker-elk/data
        target: /usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601/tcp"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_AUTOCOMPLETETIMEOUT=3000
      - KIBANA_AUTOCOMPLETETERMINATEAFTER=2500000
      - LOGGING_QUIET=false
      - LOGGING_DEST=stdout

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    volumes:
      - type: bind
        source: ./output/tshark
        target: /tshark
      - type: bind
        source: ./docker-elk/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf

