version: "3.7"

services:

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:7.9.3
    command: setup -E setup.kibana.host=kibana:5601 # - this only needs to run the first time
    environment: 
      - output.elasticsearch.hosts=["elasticsearch:9200"] 
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
    cap_add:
      - ALL
    # network_mode: host
    volumes:
      - type: bind
        source: ./docker-elk/packetbeat.yml
        target: /usr/share/packetbeat/packetbeat.yml
        read_only: true
      - type: bind
        source: ./output/pcap
        target: /output/pcap
        read_only: false
      - type: bind
        source: ./output/c-dns
        target: /output/c-dns
        read_only: false
      - type: bind
        source: ./output/pcap
        target: /usr/share/packetbeat/output/pcap
        read_only: false
    depends_on:
      - elasticsearch
      - kibana
      - logstash

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    ports:
      - "9200:9200/tcp"
    environment: 
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1024m -Xmx1024m
      - cluster.name=dnsmetricslab
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - type: bind
        source: ./docker-elk/data
        target: /usr/share/elasticsearch/data
      # - type: bind
      #   source: ./docker-elk/elasticsearch.yml
      #   target: /usr/share/elasticsearch/config/elasticsearch.yml
      #   read_only: false

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601/tcp"
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - KIBANA_AUTOCOMPLETETIMEOUT=3000
      - KIBANA_AUTOCOMPLETETERMINATEAFTER=2500000
      - LOGGING_QUIET=false
      - LOGGING_DEST=stdout

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    volumes:
      - type: bind
        source: ./output/tshark
        target: /tshark
      - type: bind
        source: ./docker-elk/logstash.conf
        target: /usr/share/logstash/pipeline/logstash.conf

